/// MIME types we support
pub const MimeType = enum {
    application_bzip2,
    application_epub,
    application_gzip,
    application_octet_stream,
    application_pdf,
    application_sqlite,
    application_tar,
    application_wasm,
    application_zip,
    application_zstd,
    audio_aac,
    audio_amr,
    audio_flac,
    audio_mp3,
    audio_ogg,
    font_otf,
    font_sfnt,
    font_ttf,
    font_woff,
    font_woff2,
    image_bmp,
    image_gif,
    image_heic,
    image_ico,
    image_jpeg,
    image_png,
    image_tiff,
    text_plain,
    video_mkv,
    video_mov,
    video_mp4,
};

///
/// Convert MIME enum → string
///
pub fn mimeToString(m: MimeType) []const u8 {
    return switch (m) {
        .application_bzip2 => "application/x-bzip2",
        .application_epub => "application/epub+zip",
        .application_gzip => "application/gzip",
        .application_octet_stream => "application/octet-stream",
        .application_pdf => "application/pdf",
        .application_sqlite => "application/vnd.sqlite3",
        .application_tar => "application/x-tar",
        .application_wasm => "application/wasm",
        .application_zip => "application/zip",
        .application_zstd => "application/zstd",
        .audio_aac => "audio/aac",
        .audio_amr => "audio/amr",
        .audio_flac => "audio/flac",
        .audio_mp3 => "audio/mpeg",
        .audio_ogg => "audio/ogg",
        .font_otf => "font/otf",
        .font_sfnt => "font/sfnt",
        .font_ttf => "font/ttf",
        .font_woff => "font/woff",
        .font_woff2 => "font/woff2",
        .image_bmp => "image/bmp",
        .image_gif => "image/gif",
        .image_heic => "image/heic",
        .image_ico => "image/x-icon",
        .image_jpeg => "image/jpeg",
        .image_png => "image/png",
        .image_tiff => "image/tiff",
        .text_plain => "text/plain",
        .video_mkv => "video/x-matroska",
        .video_mov => "video/quicktime",
        .video_mp4 => "video/mp4",
    };
}
